name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: |
          yarn install
      - name: Build (core)
        run: |
          yarn build
      - name: Publish (openai)
        run: |
          yarn workspace @beakjs/openai publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish (core)
        run: |
          yarn workspace @beakjs/core publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish (react)
        run: |
          yarn workspace @beakjs/react publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
