name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
       - name: Install dependencies and build (core)
        run: |
          yarn install
          yarn build
        working-directory: ./packages/core
      - name: Install dependencies and build (react)
        run: |
          yarn install
          yarn build
        working-directory: ./packages/react
      - name: Install dependencies and build (root)
        run: |
          yarn install
          yarn build    